### ISSUE TITLE
Specify model and temperature

### ISSUE THREAD

**Issue by giuliogcantone** [jhk0530/gemini.R#2]
Currently the release 0.4.0 has not a parameter to specify the model and the temperature.

Are these planned in next releases?

**Comment by jhk0530** [comment]
Hi, thanks for let me know. 

It isn't hard to make `temperature` available. and it may updated soon. 

But I didn't understand `model` parameter, 

I think it's fixed as `gemini-pro-vision:generateContent` or `gemini-pro:generateContent`

Would you like to provide example or reference?

**Comment by jhk0530** [comment]
I think below can updated at next release (may in near august)
- **Gemini 1.5 Flash** as `gemini-1.5-flash`
- **Gemini 1.0 Pro** as `gemini-1.0-pro`
- **Gemini 1.5 Pro** already exists.

But not sure `GEMMA` is provided with API, but I'll check later ( I don't understand `GEMMA` yet 😢 )

**Comment by jhk0530** [comment]
added `temperature`, `model`, `maxOutputTokens` in 0.5.0
