### ISSUE TITLE
Using your package (thanks!)

### ISSUE THREAD

**Issue by dylanpieper** [jhk0530/gemini.R#6]
Hi,

I'm using your package in my LLM batch processing app called [batchLLM](https://github.com/dylanpieper/batchLLM). I just wanted to put my package on your radar!

Thanks for your consideration,

Dylan

**Comment by jhk0530** [comment]
Okay, if you're using `gemini.R` and need something, let me know. 

On a different note, I think the `batchLLM` package would be more complete if you mentioned the packages in the `DESCRIPTION` as `Imports` or `Suggests`.

**Comment by erikmeesters** [comment]
Do you need to install other programs? I'm trying to run gemini.R in Rstudio, but it's not working and I have a working api key.
thanks,
Erik
