### ISSUE TITLE
new 2.0 model support

### ISSUE THREAD

**Issue by pcantalupo** [jhk0530/gemini.R#8]
Hello,
Are you planning to add support for the new Gemini 2.0 model? https://ai.google.dev/gemini-api/docs/models/gemini#gemini-2.0-flash

```
> gemini_chat("Hello!", model = "gemini-2.0-flash-exp")
✖ Error: Parameter 'a' must be one of '1.5-flash', '1.5-pro', '1.0-pro'
```

Thank you

**Comment by jhk0530** [comment]
Hi, it may possible but I'm worried about 2 things.

1. It's `experimental`, which means API may change. For example, `-exp` might be dropped.
2. Also it will, but not yet supports `audio` and `image` as output. which is not differ from `1.5-flash` I think. 

So I'm considering adding it after **it's stable**, but is there any reason to work on it before then? (Right now I'm working on something that uses audio as input).

Thanks.

**Comment by jhk0530** [comment]
Hi, @pcantalupo 
`2.0-flash-exp` is available now. 
However, default value for model is `1.5-flash` yet.
thanks.
